"$schema" = 'https://starship.rs/config-schema.json'

format = """\
[](color_orange)\
$os\
$username\
$sudo\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
[](fg:color_aqua bg:color_blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
$zig\
$elixir\
$lua\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg3 bg:color_bg1)\
$cmd_duration\
$time\
$battery\
$memory_usage\
$line_break$character"""

palette = 'weydoo_linux'

[palettes.weydoo_linux]
color_fg0 = '#ffffff'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_orange = '#d65d0e'
color_red = '#cc241d'
color_yellow = '#d79921'
color_green = "#83a598"

[sudo]
symbol = ' '
style = "fg:color_fg0 bg:color_orange"
disabled = false
format = '[as $symbol ]($style)'

[cmd_duration]
min_time = 2_000
show_milliseconds = false
style = "bg:color_bg3"
format = '[[ ⏱ $duration ](fg:color_fg0 bg:color_bg1)]($style)'

[memory_usage]
disabled = false
threshold = -1
symbol = "󰍛 "
style = "bg:color_red"
format = ' [](color_red)[ $symbol$ram ](fg:color_fg0 bg:color_red)[](fg:color_red)'

[battery]
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '
empty_symbol = "󰂎 "
unknown_symbol = "󰂑 "
format = ' [](color_aqua)[ $symbol$percentage ]($style)[](fg:color_aqua)'

[[battery.display]]
threshold = 10
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰁺 "
charging_symbol = "󰢜 "

[[battery.display]]
threshold = 20
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰁻 "
charging_symbol = "󰂅 "

[[battery.display]]
threshold = 30
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰁼 "
charging_symbol = "󰂆 "

[[battery.display]]
threshold = 40
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰁽 "
charging_symbol = "󰂇 "

[[battery.display]]
threshold = 50
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰁾 "
charging_symbol = "󰂈 "

[[battery.display]]
threshold = 60
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰁿 "
charging_symbol = "󰂉 "

[[battery.display]]
threshold = 70
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰂀 "
charging_symbol = "󰂉 "

[[battery.display]]
threshold = 80
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰂁 "
charging_symbol = "󰂊 "

[[battery.display]]
threshold = 90
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰂂 "
charging_symbol = "󰂋 "

[[battery.display]]
threshold = 100
style = "bg:color_aqua fg:color_fg0"
discharging_symbol = "󰁹 "
charging_symbol = "󰂄 "

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Téléchargements" = " "
"Musique" = "󰝚 "
"Photos" = " "
"Code" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'


[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[bun]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[zig]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[elixir]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[lua]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'


[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_green bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:color_green bg:color_bg3)]($style)'

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)[](fg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = ' [⤷](bold) [\$](bold green) '
error_symbol = ' [⤷](bold) [\$](bold red) '